dist: bionic

sudo: required

addons:
  apt:
    packages:
      - rabbitmq-server

services:
  - docker
  - postgresql
  - rabbitmq

language: perl

perl:
  - "5.26"

env:
  global:
    - WTSI_NPG_GITHUB_URL=https://github.com/wtsi-npg
    - NPG_RMQ_CONFIG='./etc/rmq_travis_config.json'
    - NPG_RMQ_HOST='localhost'
    - BATON_VERSION=2.0.0
  matrix:
    - DOCKER_IMAGE=wsinpg/ub-16.04-irods-4.2:latest
    - DOCKER_IMAGE=wsinpg/ub-12.04-irods-4.1:latest

matrix:
  allow_failures:
    - env: DOCKER_IMAGE=wsinpg/ub-16.04-irods-4.2:latest

before_install:
  - docker pull "$DOCKER_IMAGE"
  - docker run -d -p 1247:1247 "$DOCKER_IMAGE"
  - docker ps -a
  - ./scripts/travis_before_install.sh

install:
  - ./scripts/travis_install.sh

before_script:
  - ./scripts/rabbitmq_config.sh

script:
  - ./scripts/travis_script.sh
