language: perl
sudo: required

perl:
#  - "5.16"
  - "5.22-shrplib"

addons:
  postgresql: "9.3"

services:
  - rabbitmq

env:
  global:
    - PGVERSION="9.3"
    - JANSSON_VERSION="2.9"
    - BATON_VERSION="1.0.0"
    - DISPOSABLE_IRODS_VERSION="1.2"
    - RENCI_FTP_URL=ftp://ftp.renci.org
    - WTSI_NPG_GITHUB_URL=https://github.com/wtsi-npg
    - NPG_RMQ_CONFIG='./etc/rmq_travis_config.json'
    - NPG_RMQ_HOST='localhost'

  matrix:
    # - IRODS_VERSION=3.3.1 IRODS_RIP_DIR=/usr/local/irods # temporarily disable due to iRODS 3 client bug?
    - IRODS_VERSION=4.1.10 PG_PLUGIN_VERSION=1.10 PLATFORM=ubuntu12

before_install:
  # workaround for iRODS buffer overflow
  # see https://github.com/travis-ci/travis-ci/issues/5227
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
  - sudo mv /tmp/hosts /etc/hosts
  - ./scripts/travis_before_install.sh

install:
  - ./scripts/travis_install.sh

before_script:
  - ./scripts/rabbitmq_config.sh

script:
  - export PATH=$IRODS_RIP_DIR/iRODS/clients/icommands/bin:$PATH
  - ienv
  - ils
  - ilsresc -l
  - ./scripts/travis_script.sh
