dist: bionic

sudo: required

services:
  - docker
  - postgresql

language: perl

perl:
  - "5.26"

env:
  global:
    - WSI_NPG_GITHUB_URL=https://github.com/wtsi-npg
    - WSI_CONDA_CHANNEL=https://dnap.cog.sanger.ac.uk/npg/conda/devel/generic/

_iRODS_4_2_8: &iRODS_4_2_8
  env: DOCKER_IMAGE="wsinpg/ub-18.04-irods-4.2.8:latest" IRODS_VERSION="==4.2.8" BATON_VERSION=">=3.0.0"

jobs:
  include:
    - env: DOCKER_IMAGE="wsinpg/ub-16.04-irods-4.2.7:latest" IRODS_VERSION="==4.2.7" BATON_VERSION=">=3.0.0"
    - <<: *iRODS_4_2_8

  allow_failures:
    - *iRODS_4_2_8

before_install:
  - docker pull "$DOCKER_IMAGE"
  - docker run -d -p 1247:1247 "$DOCKER_IMAGE"
  - docker ps -a
  - ./scripts/travis_before_install.sh

install:
  - ./scripts/travis_install.sh

script:
  - ./scripts/travis_script.sh
